import { MAX_DELETE_AFTER_DAYS, MAX_DOMAIN_MAILBOXES, MAX_PANEL_IPS, MAX_QUOTA_MB } from './mailcow.js';
import { MAX_EXPECTED_MX } from './domains.js';
import { MAX_LICENSES, MAX_SEND_LIMIT_PER_HOUR, MAX_TERRL } from './eopSettings.js';
import { MAX_DEFERRED_COUNT, MAX_DEFERRED_MINUTES } from './nodeAlerts.js';

// The refusals of the mail node's actions: code -> [HTTP status, message]. routes/mailNode.js
// answers them ({ error, code } with the status); the panel CLI (src/cli/mailexpert.js) prints the
// same code and message. Kept here, not in the route, so the CLI never loads a route module.
export const MAIL_NODE_ERRORS = Object.freeze({
  mail_host_invalid: [400, 'Mail host must be a host name such as mail.example.com'],
  api_key_required: [400, 'API key is required'],
  quota_invalid: [400, `Quota must be a whole number of MB from 1 to ${MAX_QUOTA_MB}`],
  domain_invalid: [400, 'Domain must be a domain name such as example.com'],
  ping_url_invalid: [400, 'Ping URL must be an https address'],
  mailboxes_invalid: [400, `Mailbox limit must be a whole number from 1 to ${MAX_DOMAIN_MAILBOXES}`],
  delete_after_days_invalid: [400, `Days before a deletion must be a whole number from 1 to ${MAX_DELETE_AFTER_DAYS}`],
  mail_node_not_configured: [409, 'The mail node is not set up'],
  mailbox_not_found: [404, 'Mail node mailbox not found'],
  domain_not_ready: [400, 'Mailboxes can be created only on a domain that finished its onboarding'],
  domain_not_on_node: [404, 'The mail node has no such domain'],
  domain_not_found: [404, 'The panel does not know this domain'],
  domain_known: [409, 'The panel knows this domain already'],
  domain_already_ready: [409, 'The domain is ready already'],
  domain_not_recreated: [409, 'The node reports the creation time the panel knows already'],
  domain_node_changed: [409, 'The node reports another creation time than the one shown: reload the list'],
  node_created_required: [400, 'The creation time shown for the domain is required'],
  domain_nothing_to_restart: [409, 'The domain is at the first step with nothing to clear'],
  mail_node_host_mismatch: [409, 'The mailbox is on another mail host than the one in the mail node settings'],
  // EOP seats (services/mailNode/eopSeats.js).
  no_free_seats: [409, 'No free EOP seat: ask for more seats first'],
  seats_unknown: [409, 'The number of purchased EOP seats is not known: enter it in the EOP settings (Licenses), or reconcile with Microsoft in Mail node'],
  seat_count_invalid: [400, 'Ask for a whole number of seats from 1 to 1000'],
  seats_manual: [409, 'The tenant does not give the number of seats: it is entered in the EOP settings (Licenses)'],
  hold_days_invalid: [400, 'The hold period must be a whole number of days from 0 to 3650'],
  step_invalid: [400, 'No such onboarding step'],
  step_out_of_order: [409, 'Only the next onboarding step can be confirmed'],
  step_by_tenant_driver: [409, 'MailExpert confirms this step itself through the tenant driver'],
  mark_ready_by_tenant_driver: [409, 'With the tenant driver the domain goes through the tenant steps; it cannot be marked ready by hand'],
  outbound_connector_invalid: [400, 'Outbound connector must be its name in EAC: letters, digits, spaces, dots, dashes and underscores, up to 64 characters'],
  dbeb_external_domain_invalid: [400, 'The external domain of the DBEB contacts must be a domain name such as relay.example.com'],
  eop_host_invalid: [400, 'EOP host must be a host name such as contoso-com.mail.protection.outlook.com'],
  certificate_host_invalid: [400, 'Certificate host must be a host name such as mail.example.com'],
  dkim_mode_invalid: [400, 'DKIM mode must be mailcow or eop'],
  send_limit_invalid: [400, `Send limit must be a whole number of messages per hour from 1 to ${MAX_SEND_LIMIT_PER_HOUR}`],
  terrl_invalid: [400, `TERRL must be a whole number of recipients from 1 to ${MAX_TERRL}`],
  tenant_id_invalid: [400, 'Tenant ID must be a GUID'],
  tenant_domain_invalid: [400, "Tenant domain must be the tenant's initial domain such as contoso.onmicrosoft.com"],
  app_id_invalid: [400, 'Application ID must be a GUID'],
  thumbprint_invalid: [400, 'Certificate thumbprint must be 40 hexadecimal characters'],
  tls_policy_invalid: [400, 'TLS policy must be secure, dane, dane-only, verify, fingerprint, encrypt or default'],
  tls_parameters_invalid: [400, 'TLS policy parameters must be name=value pairs up to 255 characters that fit the policy: match= takes hostname, nexthop, dot-nexthop or host names for secure and verify, fingerprints for fingerprint (required), and nothing for the other policies'],
  panel_ips_invalid: [400, `Panel addresses must be up to ${MAX_PANEL_IPS} IP addresses or networks such as 203.0.113.10 or 203.0.113.0/28`],
  rate_limit_invalid: [400, `Send limit must be a whole number of messages from 1 to ${MAX_SEND_LIMIT_PER_HOUR} per second, minute, hour or day`],
  node_ip_invalid: [400, 'Node address must be an IPv4 address such as 203.0.113.10'],
  expected_mx_invalid: [400, `Expected MX must be up to ${MAX_EXPECTED_MX} host names such as contoso-com.mail.protection.outlook.com`],
  tenant_txt_invalid: [400, 'Verification TXT must be printable text up to 255 characters without quotes, such as MS=ms12345678'],
  dkim_cname_invalid: [400, 'DKIM selector CNAME must be a host name'],
  licenses_invalid: [400, `Licenses must be a whole number from 1 to ${MAX_LICENSES}`],
  tenant_created_invalid: [400, 'Tenant creation date must be a date such as 2026-09-14, not in the future'],
  queue_id_invalid: [400, 'Queue ID must be a Postfix queue ID such as 53A99193F13'],
  queue_action_invalid: [400, 'Queue action must be hold, unhold, deliver or delete'],
  queue_delete_unconfirmed: [400, 'Deleting a queued message must be confirmed'],
  queue_item_not_found: [404, 'The mail queue has no message with this ID'],
  queue_item_held: [409, 'A held message is released first, then delivered'],
  deferred_count_invalid: [400, `Deferred message threshold must be a whole number from 1 to ${MAX_DEFERRED_COUNT}`],
  deferred_minutes_invalid: [400, `Deferred age threshold must be a whole number of minutes from 1 to ${MAX_DEFERRED_MINUTES}`],
  alert_check_failed: [502, 'The alert check failed'],
});
